export const expenseCategories = [
  "Housing & Utilities",
  "Transportation",
  "Food & Groceries",
  "Health & Medical",
  "Planned Spending",
  "Insurance",
  "Entertainment & Leisure",
  "Shopping",
  "Education",
  "Personal Care",
  "Debt Payments",
  "Savings & Investments",
  "Gifts & Donations",
  "Travel",
  "Other",
];